version: '3'

services:
  postgresdb:
    image: postgres:latest
    container_name: ReTargetDataBase
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    ports:
      - "127.0.0.1:${PORT}:${INSIDE_PORT}"
    command: [
      "postgres",
      "-c", "max_connections=200",
      "-c", "log_statement=all",
      "-c", "password_encryption=md5"
    ]
    networks:
      - api_network
    volumes:
      - pg_data:/var/lib/postgresql/data
      - ./pg_hba.conf:/var/lib/postgresql/data/pg_hba.conf
    restart: always

  api:
    build:
      context: ..
      dockerfile: deploy/Dockerfile
    container_name: ReTargetApi
    ports:
      - "127.0.0.1:8080:8080"
    depends_on:
      - postgresdb
    networks:
      - api_network

volumes:
  pg_data:

networks:
  api_network:
    driver: bridge
