name: Run Tests & Linter

on:
  push:
    branches:
      - main
      - RE-59-add-sql-logs
  pull_request:
    branches:
      - main

jobs:
  CI:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Check current branch
        run: |
          echo "CI started in branch: $GITHUB_REF_NAME"

      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: "1.24"

      - name: Run go mod tidy (install dependencies)
        run: |
          go mod tidy
      - name: Create .env files
        run: |
          echo "Create env..."
      - name: Install golangci-lint (latest)
        run: |
          go install github.com/golangci/golangci-lint/cmd/golangci-lint@latest
          golangci-lint --version

      - name: Run tests
        run: |
          go test ./test/... -v

      - name: Run linter
        run: |
          golangci-lint run ./...
  CD:
    runs-on: ubuntu-latest
    needs: CI
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Check current branch
        run: |
          echo "CD started in branch: $GITHUB_REF_NAME"

      - name: Copy scripts
        uses: appleboy/scp-action@master
        with:
          host: ${{ secrets.SSH_HOST }}
          port: ${{ secrets.SSH_PORT }}
          username: "ubuntu"
          key: ${{ secrets.SSH_KEY }}
          source: ".github/scripts/*"
          target: "/home/ubuntu/scripts/"

      - name: Deploy from script
        uses: appleboy/scp-action@master
        with:
          host: ${{ secrets.SSH_HOST }}
          port: ${{ secrets.SSH_PORT }}
          username: "ubuntu"
          key: ${{ secrets.SSH_KEY }}
          script: |
            /home/ubuntu/scripts/deploy.sh
